# Generated by Django 2.2.7 on 2020-01-19 16:46

import apps.payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payroll')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_service_breakpoint', models.CharField(default=1870, max_length=16)),
                ('manager_service_bonus_cap', models.CharField(default=300, max_length=16)),
                ('manager_service_bonus_paid_bb_min', models.CharField(default=0.3, max_length=16)),
                ('manager_service_bonus_thpc_min', models.CharField(default=1.0, max_length=16)),
                ('rookie_raise', models.CharField(default=0.0, max_length=16)),
                ('rookie_thpc_min', models.CharField(default=1.0, max_length=16)),
                ('rookie_bb_min', models.CharField(default=0.35, max_length=16)),
                ('rookie_service_min', models.CharField(default=0.0, max_length=16)),
                ('rising_star_raise', models.CharField(default=0.5, max_length=16)),
                ('rising_star_thpc_min', models.CharField(default=1.0, max_length=16)),
                ('rising_star_bb_min', models.CharField(default=0.4, max_length=16)),
                ('rising_star_service_min', models.CharField(default=38.0, max_length=16)),
                ('star_raise', models.CharField(default=1.0, max_length=16)),
                ('star_thpc_min', models.CharField(default=1.25, max_length=16)),
                ('star_bb_min', models.CharField(default=0.45, max_length=16)),
                ('star_service_min', models.CharField(default=40.0, max_length=16)),
                ('all_star_raise', models.CharField(default=2.0, max_length=16)),
                ('all_star_thpc_min', models.CharField(default=1.5, max_length=16)),
                ('all_star_bb_min', models.CharField(default=0.5, max_length=16)),
                ('all_star_service_min', models.CharField(default=42.0, max_length=16)),
                ('mvp_raise', models.CharField(default=3.0, max_length=16)),
                ('mvp_thpc_min', models.CharField(default=1.75, max_length=16)),
                ('mvp_bb_min', models.CharField(default=0.55, max_length=16)),
                ('mvp_service_min', models.CharField(default=44.0, max_length=16)),
                ('mvp_gold_raise', models.CharField(default=4.0, max_length=16)),
                ('mvp_gold_thpc_min', models.CharField(default=2.0, max_length=16)),
                ('mvp_gold_bb_min', models.CharField(default=0.6, max_length=16)),
                ('mvp_gold_service_min', models.CharField(default=46.0, max_length=16)),
                ('mvp_platinum_raise', models.CharField(default=5.0, max_length=16)),
                ('mvp_platinum_thpc_min', models.CharField(default=2.5, max_length=16)),
                ('mvp_platinum_bb_min', models.CharField(default=0.65, max_length=16)),
                ('mvp_platinum_service_min', models.CharField(default=48.0, max_length=16)),
                ('take_hm_bonus_lvl_1_sales_min', models.CharField(default=1.0, max_length=16)),
                ('take_hm_bonus_lvl_1_multiplier', models.CharField(default=0.1, max_length=16)),
                ('take_hm_bonus_lvl_2_sales_min', models.CharField(default=2.0, max_length=16)),
                ('take_hm_bonus_lvl_2_multiplier', models.CharField(default=0.2, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylist_analysis', models.FileField(upload_to=apps.payroll.models.user_directory_path)),
                ('tips_by_employee', models.FileField(upload_to=apps.payroll.models.user_directory_path)),
                ('hours_week_1', models.FileField(upload_to=apps.payroll.models.user_directory_path)),
                ('hours_week_2', models.FileField(upload_to=apps.payroll.models.user_directory_path)),
                ('client_retention', models.FileField(upload_to=apps.payroll.models.user_directory_path)),
                ('employee_service_efficiency', models.FileField(upload_to=apps.payroll.models.user_directory_path)),
            ],
        ),
    ]
