# Generated by Django 2.2.7 on 2019-12-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsettings',
            name='all_star_bb_min',
            field=models.CharField(default=0.5, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='all_star_raise',
            field=models.CharField(default=2.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='all_star_service_min',
            field=models.CharField(default=42.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='all_star_thpc_min',
            field=models.CharField(default=1.5, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='manager_service_bonus_cap',
            field=models.CharField(default=300, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='manager_service_bonus_paid_bb_min',
            field=models.CharField(default=0.3, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='manager_service_bonus_thpc_min',
            field=models.CharField(default=1.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='manager_service_breakpoint',
            field=models.CharField(default=1870, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_bb_min',
            field=models.CharField(default=0.55, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_gold_bb_min',
            field=models.CharField(default=0.6, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_gold_raise',
            field=models.CharField(default=4.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_gold_service_min',
            field=models.CharField(default=46.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_gold_thpc_min',
            field=models.CharField(default=2.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_platinum_bb_min',
            field=models.CharField(default=0.65, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_platinum_raise',
            field=models.CharField(default=5.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_platinum_service_min',
            field=models.CharField(default=48.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_platinum_thpc_min',
            field=models.CharField(default=2.5, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_raise',
            field=models.CharField(default=3.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_service_min',
            field=models.CharField(default=44.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='mvp_thpc_min',
            field=models.CharField(default=1.75, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='rising_star_bb_min',
            field=models.CharField(default=0.4, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='rising_star_raise',
            field=models.CharField(default=0.5, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='rising_star_service_min',
            field=models.CharField(default=38.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='rising_star_thpc_min',
            field=models.CharField(default=1.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='rookie_service_min',
            field=models.CharField(default=0.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='star_bb_min',
            field=models.CharField(default=0.45, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='star_raise',
            field=models.CharField(default=1.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='star_service_min',
            field=models.CharField(default=40.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='star_thpc_min',
            field=models.CharField(default=1.25, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='take_hm_bonus_lvl_1_multiplier',
            field=models.CharField(default=0.1, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='take_hm_bonus_lvl_1_sales_min',
            field=models.CharField(default=1.0, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='take_hm_bonus_lvl_2_multiplier',
            field=models.CharField(default=0.2, max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='take_hm_bonus_lvl_2_sales_min',
            field=models.CharField(default=2.0, max_length=16),
        ),
    ]
